notifications:
  email: false
language: cpp
dist: bionic
sudo: required

addons:
    apt:
        update: true
        packages:
        - gcc
        - cmake
        
before_script:
    - sudo apt-get -y install libsfml-dev
    #Build wxWidgets
    - sudo apt-get -y install build-essential libgtk2.0-dev libgtk-3-dev libglw1-mesa libglw1-mesa-dev libglu1-mesa-dev
    - git clone --recurse-submodules --branch v3.1.3 https://github.com/wxWidgets/wxWidgets
    - cd wxWidgets
    - mkdir gtk-build
    - cd gtk-build
    - ../configure --with-gtk=3 --with-opengl
    - make -j4
    - sudo make install
    - sudo ldconfig
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    
script:
    - mkdir bin
    - cd bin
    - cmake -DCMAKE_MODULE_PATH="/usr/share/SFML/cmake/Modules/" -DCMAKE_BUILD_TYPE=Debug ..
    - make -j4