notifications:
  email: false
language: cpp
dist: focal
sudo: required

addons:
    apt:
        update: true
        packages:
        - gcc
        - cmake
        - git
        - libsfml-dev
        - libgl1-mesa-dev
        
before_script:
    - git clone https://github.com/ocornut/imgui.git
    - git clone https://github.com/eliasdaler/imgui-sfml.git
    - mkdir imgui-sfml/build
    - cd imgui-sfml/build
    - cmake -DBUILD_SHARED_LIBS=ON -DIMGUI_DIR:FILEPATH=../imgui ..
    - sudo cmake --build . --target install
    - cd ../../
    
script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build . --config Debug --target all -- -j