notifications:
  email: false
language: cpp
dist: bionic
sudo: required

addons:
    apt:
        update: true
        packages:
        - gcc
        - cmake
        
before_script:
    - sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
    - sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.3/ubuntu/ bionic universe'
    - sudo apt-get update
    - sudo apt-get install -y libwxbase3.1-0-unofficial3 libwxbase3.1unofficial3-dev libwxgtk3.1-0-unofficial3 libwxgtk3.1unofficial3-dev wx3.1-headers wx-common
    - sudo apt-get install -y libsfml-dev
    
script:
    - mkdir bin
    - cd bin
    - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MODULE_PATH="/usr/share/SFML/cmake/Modules/" ..
    - make -j4