notifications:
  email: false
language: cpp
dist: bionic
sudo: required

addons:
    apt:
        update: true
        packages:
        - gcc
        - cmake
        
before_script:
    - sudo apt-get -y install libsfml-dev
    - sudo apt-get -y install wx3.0-headers libwxgtk3.0-gtk3-dev
    
script:
    - mkdir bin
    - cd bin
    - cmake -DCMAKE_MODULE_PATH="/usr/share/SFML/cmake/Modules/" -DCMAKE_BUILD_TYPE=Debug ..
    - make -j4