notifications:
  email: false
language: cpp
dist: xenial
sudo: required

addons:
    apt:
        update: true
        packages:
        - cmake
        
before_script:
    - sudo apt-get -y install libsfml-dev
    
script:
    - cmake -DCMAKE_MODULE_PATH="/usr/share/SFML/cmake/Modules/" -DCMAKE_BUILD_TYPE=Debug .
    - make -j4